### ISSUE TITLE
arizona_tpl_compile.erl: think about using modules to be the view (compile/1)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [arizona-framework/arizona#119]
It eases maintenance...

**Comment by williamthome** [comment]
I don't have a clear idea of what this means. I've marked it as resolved in https://github.com/arizona-framework/arizona/pull/164, but I'm not sure.

**Comment by paulo-ferraz-oliveira** [comment]
It comes from the linked pull request: there was a bunch of stuff I moved from code to Issues.

**Comment by williamthome** [comment]
Hmm, ok, so #164 will close this issue. Thanks, @paulo-ferraz-oliveira!
