### ISSUE TITLE
Org. level: think about https://github.com/organizations/arizona-framework/settings/security

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [arizona-framework/arizona#131]
@williamthome, if you have 2FA activated for your account (I do) it's just a question of ✅ing `Require two-factor authentication for everyone in the Arizona Framework organization.` and moving on 😄

**Comment by williamthome** [comment]
Yes, I have 2FA activated.

**Comment by paulo-ferraz-oliveira** [comment]
It's done 😄
