### ISSUE TITLE
Org. level: think about https://github.com/organizations/arizona-framework/settings/publisher

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [arizona-framework/arizona#132]
Ref.: https://github.com/arizona-framework/arizona/issues/21#issuecomment-2198549716

**Comment by williamthome** [comment]
Let's use an e-mail with Arizona's domain :slightly_smiling_face:

**Comment by paulo-ferraz-oliveira** [comment]
> Let's use an e-mail with Arizona's domain 🙂

Even better. Perfect stuff!

**Comment by williamthome** [comment]
Done :tada:
