### ISSUE TITLE
Allow render `ok` atom values

### ISSUE THREAD

**Issue by williamthome** [arizona-framework/arizona#175]
Currently, the renderer module ignores any `ok` value, i.e, any `ok` atom is not rendered. See [here](https://github.com/arizona-framework/arizona/blob/9cbd1b6639c4afb2727a16c17498e04c48e5fac0/src/arizona_tpl_render.erl#L145). Why? The idea was to be able to use `io:format` and not produce any output, e.g.:
```
<div>
    {io:format("~p~n", [_@foo])}
</div>
```
`io:format("~p~n", [_@foo])` will print the foo assign at the shell, but the render output is: `<div></div>`. The `ok` atom returned by the `io:format` Is suppressed. But this is an odd behavior. 

Without this behavior, a workaround for this is:
```
<div>
    {io:format("~p~n", [_@foo]), <<>>}
</div>
```
In this way, foo is printed, but the expression returns an empty binary, so the result is as expected: `<div></div>`.

I think debugging values in the shell is helpful in some situations. 

I'll propose four possible solutions:
1. An `arizona_template` module with a `debug` or `format` function which prints values but returns an empty binary
2. An `arizona_io` module with a `format` function function which prints values but returns an empty binary
3. Remove this behavior and require the consumer to return an empty binary (that's the current behavior of the new renderer proposed in #168)
4. Leave as is

**Comment by paulo-ferraz-oliveira** [comment]
I think the return value has to be explicit: i.e., no magic. We can still use `io:format`, or `erlang:display` or something like this to debug in the shell, but the execution's result should make its way to the template.

**Comment by paulo-ferraz-oliveira** [comment]
I think thus, if I understood it correctly, my choice would go to `3.`.

**Comment by williamthome** [comment]
I also go with option 3. I'll close it in https://github.com/arizona-framework/arizona/pull/168.
